# Helix with Steel plugin support (mattwparas/helix, packaged in nixpkgs as
# `steelix`), exposed as a second editor binary `hh`.
#
# The stock helix config in ./helix.nix is left untouched. `hh` reads the same
# ~/.config/helix/config.toml, languages.toml and themes/ as `hx`, and adds
# ~/.config/helix/init.scm (generated by nhx) plus the plugins installed under
# $STEEL_HOME/cogs. Stock `hx` ignores both, so the two can coexist.
{
  lib,
  pkgs,
  nhx,
  ...
}:
let
  # Wrapper instead of installing steelix directly: steelix also ships `bin/hx`,
  # which would collide with the stock helix package in home.packages.
  helix-steel = pkgs.writeShellScriptBin "hh" ''
    export STEEL_HOME="''${STEEL_HOME:-$HOME/.local/share/steel}"
    exec ${lib.getExe pkgs.steelix} "$@"
  '';
in
{
  imports = [
    nhx.homeManagerModules.nhx
  ];

  home.packages = [
    helix-steel
  ];

  programs.nhx = {
    enable = true;

    # null: nhx must not add steelix's own `hx` to the profile (see wrapper above).
    package = null;

    # settings / languages are intentionally not set here. programs.helix owns
    # config.toml and languages.toml, and `hh` picks them up as-is.

    steel = {
      enable = true;
      # steel-language-server is not installed; avoid a dangling LSP entry.
      lsp.enable = false;

      # Raw Scheme appended to init.scm. Keybinds for plugin commands live
      # here, not in helix.nix: stock `hx` rejects unknown typable commands.
      extra = ''
        (keymap (global)
                (normal (space (e ":forest-open"))))
      '';
    };

    # Mentioning a plugin installs it into $STEEL_HOME/cogs.
    # `enable = true` adds its (require ...) line to init.scm.
    # Available names: see nhx/pkgs/helixPlugins in the nhx repo.
    plugins = {
      # File explorer tree in a sidebar (:forest-open). Defaults: style "snacks",
      # position "left". Set config.{style,position,ignore} to tune.
      forest.enable = true;

      # Interactive find-and-replace (:scooter)
      scooter.enable = true;

      # Other candidates, uncomment to try:
      # hx-tmux-navigator.enable = true; # tmux pane <-> helix split navigation
      # trail.enable = true;             # recent project picker
      # anchor.enable = true;            # save/restore open buffers per workspace
      # cliff.enable = true;             # tree-sitter code folding
      # zen-mode.enable = true;          # centered, gutter-less writing mode
    };
  };
}
