{
  pkgs,
  ...
}: 

{
  home = {
    file = {
      ".zshrc" = {
        text = ''
          # Generated by Home Manager
          eval "$(/opt/homebrew/bin/brew shellenv)"
          source /opt/homebrew/share/powerlevel10k/powerlevel10k.zsh-theme
          [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

          tmux source-file ~/.config/tmux/tmux.conf

          export GEMINI_API_KEY=%GEMINI_KEY%
          export AIDER_AUTO_COMMITS=False
          export AIDER_EDITOR="hx"
        '';
      };
      ".p10k.zsh" = {
        source = builtins.path {
          path = ./config/.p10k.zsh;
        };
      };
    };
  };

  programs = {
    zsh = {
      enable = true; 
      plugins = [
        {
          name = "powerlevel10k";
          src = pkgs.zsh-powerlevel10k;
          file = "share/zsh-powerlevel10k/powerlevel10k.zsh-theme";
        }
      ];
      shellAliases = {
        g = "git";
        h = "hx";
        f = "fzf";
        lg = "lazygit";
        ai = "aider --model gemini/gemini-2.5-flash-preview-05-20";
      };
    };

    home-manager.enable = true; # Let Home Manager install and manage itself.
  };
}
