{
  pkgs,
  ...
}: 

{
  home = {
    file = {
      ".zshrc" = {
        text = ''
          # Generated by Home Manager
          eval "$(/opt/homebrew/bin/brew shellenv)"
          source /opt/homebrew/share/powerlevel10k/powerlevel10k.zsh-theme
          [[ ! -f ./.p10k.zsh ]] || source ./.p10k.zsh
        '';
      };
      ".gitignore_global" = {
        source = builtins.path {
          path = ../shared/config/.gitignore_global;
        };
      };
      ".p10k.zsh" = {
        source = builtins.path {
          path = ./config/.p10k.zsh;
        };
      };
    };

    sessionVariables = {
      DIRENV_LOG_FORMAT = "";
    };

    stateVersion = "22.05";

    packages = with pkgs; [
      vim
      gnupg

      # Node 
      nodejs
      nodePackages.npm # globally install npm
      yarn
      nodePackages.prettier
      nodePackages.nodemon
      nodePackages.typescript-language-server

      # Rust
      rustc
      cargo
      rustfmt

      python3
      go
    ];
  };

  programs = {
    zsh = {
      enable = true; 
      plugins = [
        {
          name = "powerlevel10k";
          src = pkgs.zsh-powerlevel10k;
          file = "share/zsh-powerlevel10k/powerlevel10k.zsh-theme";
        }
      ];
      shellAliases = {
        g = "git";
        h = "hx";
      };
    };

    direnv = {
      enable = true;
      nix-direnv.enable = true;
    };

    git = {
      enable = true;
      userName = "%GIT_NAME";
      userEmail = "%GIT_EMAIL";

      extraConfig = {
        init.defaultBranch = "main";
        core = {
          editor = "vim";
          excludesFile = "~/.gitignore_global";
        };
        pull.rebase = true;
        rebase.autoStash = true;
        alias = {
          gone = "!f() { git fetch --all --prune; git branch -vv | awk '/: gone]/{print $1}' | xargs git branch -D; }; f";
          a = "add";
          aa = "add --all";
          ai = "add -i";
          b = "branch";
          ba = "branch -a";
          bd = "branch -d";
          bdd = "branch -D";
          br = "branch -r";
          bc = "rev-parse --abbrev-ref HEAD";
          bu = "!git rev-parse --abbrev-ref --symbolic-full-name \"@{u}\"";
          bs = "!git-branch-status";
          c = "commit";
          cm = "commit -m";
          cl = "clone";
          d = "diff";
          f = "fetch";
          fo = "fetch origin";
          l = "log --oneline";
          lg = "log --oneline --graph --decorate";
          m = "merge";
          ma = "merge --abort";
          mc = "merge --continue";
          ms = "merge --skip";
          ch = "checkout";
          chmst = "checkout master";
          chmain = "checkout main";
          chb = "checkout -b";
          ph = "push";
          phf = "push --force-with-lease";
          pl = "pull";
          pb = "pull --rebase";
          plo = "pull origin";
          pro = "pull --rebase origin";
          plom = "pull origin master";
          rb = "rebase";
          rba = "rebase --abort";
          rbc = "rebase --continue";
          rbi = "rebase --interactive";
          rbs = "rebase --skip";
          uncommit = "reset HEAD~1";
          s = "status";
          st = "stash"; 
          sc = "stash clear";
          sd = "stash drop";
          sl = "stash list";
          sp = "stash pop";
          ss = "stash save";
          ssh = "stash show";
          t = "tag";
          td = "tag -d";
        };
      };
    };

    home-manager.enable = true; # Let Home Manager install and manage itself.
  };
}
