name: Build Template

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Apply CI User Info
        run: |
          # Set basic values for variables
          export USERNAME="ciuser"
          export GIT_EMAIL="ciuser@example.com"
          export GIT_NAME="CI User"
          export PRIMARY_IFACE="eth0"
          export HOST_NAME="ci-host"
          export BOOT_DISK="sda"

          # Function to replace tokens in each file
          replace_tokens() {
            local file="$1"
            if [[ $(basename "$file") != "apply" ]]; then
              sed -i -e "s/%USER%/$USERNAME/g" -e "s/%EMAIL%/$GIT_EMAIL/g" -e "s/%NAME%/$GIT_NAME/g" \
                     -e "s/%INTERFACE%/$PRIMARY_IFACE/g" -e "s/%DISK%/$BOOT_DISK/g" -e "s/%HOST%/$HOST_NAME/g" "$file"
            fi
          }

          # Traverse directories and replace tokens in each Nix file
          export -f replace_tokens
          find . -type f -exec bash -c 'replace_tokens "$0"' {} \;

      - name: Build Nix Flake
        run: |
          echo "Building Flake..."
          if nix build --extra-experimental-features 'nix-command flakes' .#nixosConfigurations.x86_64-linux.config.system.build.toplevel; then
            echo "success=true" >> $GITHUB_ENV
          else
            echo "Build failed, listing flake.lock for debugging:"
            cat flake.lock
            echo "success=false" >> $GITHUB_ENV
            exit 1
          fi

      - name: Determine build result
        id: build-result
        run: echo "success=${{ env.success }}" >> $GITHUB_OUTPUT
